### PR TITLE
Use the logo configured with html_logo.

### PR DESCRIPTION
**Pull request by jgosmann**
Also fixes the link to go the main file instead of always nengo.ai.

### CODE REVIEW

**Comment by tbekolay** [comment]
Hm... so I think this will have to be a bit of a discussion, as I think the intention is for the very top navbar to always contain the same links. Right now each of the docs pages are built separately and so are kind of separate websites, but I think we want the user to feel as though they are actually just on one website (nengo.ai) and the fact that we generate them all separately under the hood is not something that should be apparent to them. So, I would expect that clicking things on the top navbar should always take you to the same place.

The left sidebar, on the other hand, is where project-specific stuff is designed to live, so what do you think about placing the project logo somewhere in the left sidebar? Could be at the top in the box, or above the box, or at the bottom somewhere. I worry a bit about having two logos so close, but probably there's a way to make it work and make it obvious that the left sidebar is project-specific links.

**Comment by jgosmann** [comment]
No idea what the best thing to do is, but currently the only indication what project's documentation your are viewing is the favicon and the tab name (and there only at the end which might be easily cut off). In the sidebar is currently also no link to jump back to the projects main page.

**Comment by tbekolay** [comment]
Yeah, what about moving the changes in this PR from the navbar to the sidebar?

**Comment by jgosmann** [comment]
Did this in the last commit.

**Review by tbekolay — APPROVED** [review]
I added a logo to the test docs that are part of this repo to see how it renders. LGTM!

**Pull request merged**
