### PR TITLE
Sidebar fixes

### PR DESCRIPTION
**Pull request by drasmuss**
This removes the extra sidebar padding pointed out in #9, and makes the sidebar sticky again.

### CODE REVIEW

**Comment by tbekolay** [comment]
This branch breaks the top navbar for me (puts it at the bottom of the page) and hides the footer ... might be some bad HTML nesting? Will look into it.

**Comment by drasmuss** [comment]
Hmm it didn't used to do that, but I see the same thing now.  Maybe a sphinx update or something?

**Comment by tbekolay** [comment]
I'm on 1.6.7 so probably not Sphinx... it seems like more of a bootstrap issue, as what I'm seeing is that the `header` element is being moved to after the main `div` even though it starts off before it. Not sure why such an old version of bootstrap would be changed, but I'll see if anyone else has reported it.

**Comment by tbekolay** [comment]
OK pushed some commits, which work for me. It's a somewhat cleaner change in that there were previously two spots for random custom JS code (custom.js and in `layout.html` itself) and it seems like putting them together fixed it :man_shrugging:

**Review by tbekolay — APPROVED** [review]
This is good by me now, will merge on @drasmuss's OK.

**Comment by drasmuss** [comment]
Looks good to me!

**Pull request merged**
