### PR TITLE
Add AutoAutoSummary extension

### PR DESCRIPTION
**Pull request by drasmuss**
Used to automatically generate Autosummaries for classes/modules.

### CODE REVIEW

**Comment by drasmuss** [comment]
Random thought: since we tend to always use this with `:nosignatures:`, we could make that the default for AutoAutoSummary. Would avoid having to specify that, but it'd mean that there's a different default for AutoSummary vs AutoAutoSummary, which could be confusing.

**Comment by tbekolay** [comment]
Could make it something configurable in `conf.py` and configure it there, like we do with `autodoc_default_options`.

**Review by tbekolay — APPROVED** [review]
I made https://github.com/sphinx-doc/sphinx/pull/6792 to deal with the issue we were having with nested autosummaries with the module repeated twice. The main dev marked it `wontfix`, so I suggested a few alternatives, one of which seems like it might be somewhat convenient but would require a change to autoautosummary. Since that likely won't happen anytime soon, I pushed a commit that does the monkeypatch fix.

One thing that I'd like to get @drasmuss's thoughts on before merging is whether we should limit the Sphinx versions that we're using? Right now we're depending on `>=1.8`. We could do `>=1.8,<=2.2.1` so that Sphinx upgrades don't break Nengo Sphinx Theme (if `import_by_name` changes significantly, for example). Or, we could pin to a known working version (`==2.2.1`) and be very deliberate about supporting certain Sphinx versions. I think for me I'm OK leaving it at just `>=1.8` for now, but thought I would check before merging.

**Comment by drasmuss** [comment]
Yeah I think since we're only really using this internally, and we can expect to have a pretty quick turnaround if a sphinx update does break things, just leaving the sphinx dependency open-ended sounds good to me.

**Pull request merged**
